### ISSUE TITLE
custom ng-disabled doesn't work on submit-button directive

### ISSUE THREAD

**Issue by altryne** [bendrucker/angular-form-state#2]
Hey,
So it turns out, that using ng-disabled doesn't work on the submit-button directive

We have code like so:
```<button type="submit" class="btn btn-primary" tabindex="0"
                            ng-class="{ 'btn-locked' : ClearCtrl.bank_form.$invalid }"
                            submit-button
                            ng-disabled="ClearCtrl.bank_form.$invalid"
                            pending="Submitting...">Continue to clear</button>```

And when the form returns from ajax with an error, the button stops being "pending" and removes the disabled state, and then the ng-disabled doesn't work anymore.

Any way around this?

**Comment by bendrucker** [comment]
Can you put together a repo that reproduces this? I have basically the same functionality (disable button either when form is invalid or submission is in flight). I just went through the following steps:

1. Complete the form (button becomes enabled)
2. Use Chrome dev tools to simulate no connection
3. Click button to submit form (error message appears)
4. Delete the contents of a required field (button becomes disabled again)

If you're doing something differently let me know. It was definitely my intent to allow `ngDisabled` to be combined with `submitButton`.

**Comment by altryne** [comment]
http://plnkr.co/edit/idq8oqxrQQW1e39yfmmZ?p=preview

It's a little messy, but the idea is there, a form submits, then after a timeout the promise is rejected
On the reject handler, I use $setValidity and set a custom validation on a form element.
for is not $valid but the submit button is not disabled

**Comment by bendrucker** [comment]
Alrighty. So this is part a bug in your code and part something for me to think about how to address properly. 

By handling the submission error (i.e. `promise.then(noop, handle)` or better `promise.catch(handle)`) you're preventing form-state from knowing that the submission failed. Promises are immutable and you're changing the end state from rejected to succeeded when you handle errors. Make sure you return `$q.reject(err)` from your error handler if you want form-state to handle the error too. That's just an aside and might only be relevant to this example.

So here's what's really up. You change the validity of the control and that triggers the disabling of the button via `ngDisabled`. form-state does not know that submission is done until *after* that's happened. It enables the button because the form is no longer pending. 

The easy option here is to provide a way for you to pass a callback via the directive API. That's gross and I really want to avoid it. I'd much treat `ngDisabled` as a special case and watch its value while the form is in flight. The whole API could use a thorough cleanup. Give me till the end of the week and I'll ship a 2.0 that'll work for your example as given.

Feel free to hit me with any other feature requests or concerns while I'm revamping.

**Comment by altryne** [comment]
What about watching the form $isValid state and making the button disabled/enabled only if $isValid is true for the form?

**Comment by bendrucker** [comment]
Most of the time that should have the same result but it's not correct. You could add some other expression value to `ngDisabled`, e.g. `form.$invalid && myProp`. What you're doing by calling `$setValidity` should not work any differently than if you did `$scope.myProp = true`.

**Comment by bendrucker** [comment]
Sorry for forgetting about this! Should be all good to go.

**Comment by altryne** [comment]
Thanx! I'll check this out, is it out on bower?

**Comment by bendrucker** [comment]
Yup, the `v2.0.0` tag has a UMD build
